/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/U4FXVEGv6ko
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Card } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import { PositionPreview } from "./position-preview"

export function Leaderboards() {
  return (
    <div className="p-4 space-y-4">
      <h1 className="text-3xl font-bold">Leaderboards</h1>
      <div className="flex justify-between items-center">
        <h2 className="text-xl font-semibold">Top Traders</h2>
        <Select>
          <SelectTrigger id="timeframe" className="w-24">
            <SelectValue placeholder="All" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="All">All</SelectItem>
            <SelectItem value="30d">30d</SelectItem>
            <SelectItem value="60d">60d</SelectItem>
            <SelectItem value="90d">90d</SelectItem>
          </SelectContent>
        </Select>
      </div>
      <div className="space-y-2">
        {Array(5)
          .fill(0)
          .map((_, i) => (
            <Card key={i} className="flex items-center p-3">
              <Avatar className="mr-4">
                <AvatarImage src="/placeholder-user.jpg" alt="Maxine Shu" />
                <AvatarFallback>MS</AvatarFallback>
              </Avatar>
              <div className="flex-1">
                <p className="font-semibold">Maxine Shu</p>
                <p className="text-sm text-muted-foreground">@maxs</p>
              </div>
              <div className="flex items-center">
                <p className="font-semibold mr-2">+32 %</p>
                <ArrowUpIcon className="text-green-500 w-4 h-4" />
              </div>
            </Card>
          ))}
      </div>
      <Button className="w-full">View More</Button>

      <div className="w-full p-3"></div>

      <div className="flex justify-between items-center">
        <h2 className="text-xl font-semibold">Top Positions</h2>
        <Select>
          <SelectTrigger id="timeframe" className="w-24">
            <SelectValue placeholder="All" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="All">All</SelectItem>
            <SelectItem value="30d">30d</SelectItem>
            <SelectItem value="60d">60d</SelectItem>
            <SelectItem value="90d">90d</SelectItem>
          </SelectContent>
        </Select>
      </div>
      <div className="space-y-2">
        {Array(5)
          .fill(0)
          .map((_, i) => (
            <PositionPreview key={i} />
          ))}
      </div>
      <Button className="w-full">View More</Button>

      <div className="w-full p-6"></div>
    </div>
  )
}

function ArrowUpIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m5 12 7-7 7 7" />
      <path d="M12 19V5" />
    </svg>
  )
}
